#!/bin/bash
crumb_id=$(curl -s 'http://localhost:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)' -u kumar:1234)
curl -s -XPOST 'http://localhost:8080/reload' -u kumar:1234 -H "$crumb_id"
